In [1]:
#Array operations with Numpy

import numpy 

u = numpy.array((0,1,2,3,4,5))

for i in range(1,len(u)):
    print(u[i]-u[i-1])
    
print(u[1:])

print(u[0:-1])

u[1:] - u[0:-1]

1
1
1
1
1
[1 2 3 4 5]
[0 1 2 3 4]


array([1, 1, 1, 1, 1])

In [5]:

import numpy
nx = 81 
ny = 81
nt = 100
c= 1

dx = 2/ (nx-1)
dy = 2/ (ny-1)

sigma = .2

dt = sigma *dx 

x = numpy.linspace(0,2,nx)
y = numpy.linspace(0,2,ny)

print('x:',x)
print('y:',y)

u = numpy.ones((ny,nx))    ##create a 1xn vector of 1's
un = numpy.ones((ny,nx))


print(u)
print(un)

##Assign initial conditions

u[int(.5/dy):int(1/dy+1),int(.5/dx):int(1/dx+1)]=2

numpy,ones((0:1,0:1))


SyntaxError: invalid syntax (<ipython-input-5-910685ecd5ce>, line 31)